spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Altere para create-drop para limpar o banco ao fechar,
# ou mantenha create para apenas recriar ao iniciar.
spring.jpa.hibernate.ddl-auto=update

# REMOVIDO o ponto e vírgula do final
spring.sql.init.mode=always

# ADICIONADO: Essencial para evitar o erro de "tabela não encontrada"
# Ele faz o Spring esperar o Hibernate criar as tabelas antes de rodar o import.sql
spring.jpa.defer-datasource-initialization=true

# Opcional: Útil para debugar e ver se o script está sendo lido
#spring.jpa.show-sql=true